name: Validate Portal JSONs

on:
  push:
    paths:
      - '_data/portals/*.json'
  pull_request:
    paths:
      - '_data/portals/*.json'
  workflow_dispatch:

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /_data/portals/PortalGroup.schema.json
          INPUT_JSONS:  /_data/portals/admin.json,/_data/portals/thirdparty.json,/_data/portals/us-govt.json,/_data/portals/user.json
